# -*- coding: utf-8 -*-
"""Dimensionality_reduction_PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pt4UsG_fibKzrzsk9EaBRl9K1ENddPaF
"""

import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt

!pip install mglearn

import mglearn

mglearn.plots.plot_pca_illustration()
plt.show()



"""# PCA (Principal Component Analysis)"""

# Create a signal with only 2 useful dimensions
x1 = np.random.normal(size=100)
x2 = np.random.normal(size=100)
x3 = x1 + x2
X = np.c_[x1, x2, x3]

X.shape
X[:5,:]

from sklearn import decomposition
pca = decomposition.PCA()
pca.fit(X)

print(pca.explained_variance_)

# As we can see, only the 2 first components are useful
pca.n_components = 2
X_reduced = pca.fit_transform(X)
X_reduced.shape
X_reduced[:5,:]

